import type { Metadata } from "next";
import "./globals.css"; // Import the global CSS
import { ClerkProvider } from "@clerk/nextjs";
import { FormProvider } from "@/context/FormContext";
import Navbar from "@/components/Navbar";
import ThemeProviderWrapper from "@/components/Themewraper";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <FormProvider>
        <html lang="fa" dir="rtl">
          <body>
            <ThemeProviderWrapper>
              <Navbar />
              {children}
            </ThemeProviderWrapper>
          </body>
        </html>
      </FormProvider>
    </ClerkProvider>
  );
}
